app = "replace-with-your-bot-app-name"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[env]
  IPC_ENABLE = "false"
  LAVALINK_IDENTIFIER = "DEFAULT"
  LAVALINK_PORT = "2333"
  LAVALINK_SECURE = "false"
  MONGODB_NAME = "vocard"

[processes]
  app = "python -u main.py"

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
