app = "music-discord-bot-knqtgs"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[env]
  IPC_ENABLE = "false"
  LAVALINK_IDENTIFIER = "DEFAULT"
  LAVALINK_PORT = "2333"
  LAVALINK_SECURE = "false"
  MONGODB_NAME = "vocard"

# Discord bot adalah background worker, tidak perlu HTTP service
# Fly akan menganggap app healthy jika process berjalan
[experimental]
  auto_rollback = true

# Important: Jangan tambahkan [[services]] atau [http_service]
# Discord bot tidak butuh exposed ports

[vm]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512
